sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t joconstantine/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joconstantine/docker-react npm run test
